//
//  main.swift
//  diarization-lab
//
//  Usage: swift run -c release diarization-lab <render|evaluate|align|bench|all> [output-dir]
//
//  Rendered audio goes to `.fixtures/` beside the package (ignored by Git).
//  Reports go to `results/`.
//

import DiarizationCore
import Foundation

let packageRoot = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
let fixtureDirectory = packageRoot.appendingPathComponent(".fixtures", isDirectory: true)
let resultsDirectory = packageRoot.appendingPathComponent("results", isDirectory: true)
let command = CommandLine.arguments.dropFirst().first ?? "all"

func renderAll() throws -> [(RenderedFixture, [Float])] {
    try FileManager.default.createDirectory(at: fixtureDirectory, withIntermediateDirectories: true)
    let renderer = Renderer(directory: fixtureDirectory)
    var out = [(RenderedFixture, [Float])]()
    var truth = [RenderedFixture]()
    for spec in corpus() {
        let (fixture, samples) = try renderer.render(spec)
        try Renderer.write(samples, to: fixtureDirectory.appendingPathComponent("\(spec.name).wav"))
        out.append((fixture, samples))
        truth.append(fixture)
    }
    let encoder = JSONEncoder()
    encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
    try FileManager.default.createDirectory(at: resultsDirectory, withIntermediateDirectories: true)
    try encoder.encode(truth).write(to: resultsDirectory.appendingPathComponent("ground-truth.json"))
    return out
}

func write(_ text: String, _ name: String) throws {
    try FileManager.default.createDirectory(at: resultsDirectory, withIntermediateDirectories: true)
    try text.write(to: resultsDirectory.appendingPathComponent(name), atomically: true, encoding: .utf8)
    print(text)
}

func evaluate(_ fixtures: [(RenderedFixture, [Float])]) async throws {
    var evaluator = Evaluator(fixtures: fixtures)
    let test = fixtures.indices.filter { fixtures[$0].0.split == "test" }
    var report = "# Evaluation\n\nGenerated by `diarization-lab evaluate`. Percentages are of scored reference speech time (collar 0.25 s). See README for definitions.\n\n"
    var all = [ConfigurationResult]()
    for embedding in evaluator.embeddings {
        for mode in [ClusteringConfiguration.Mode.postMeeting, .live] {
            let (threshold, margin, log) = try await evaluator.tune(embedding: embedding, mode: mode)
            report += "## \(embedding.name), \(mode.rawValue)\n\nTuned on dev: \(log)\n\n"
            for activity in ActivitySource.allCases {
                let configuration = ClusteringConfiguration(mode: mode, threshold: threshold, margin: margin)
                let result = try await evaluator.run(indices: test, embedding: embedding, activity: activity, configuration: configuration)
                all.append(result)
                report += "### Test split, \(activity.rawValue) activity\n\n" + Report.table(result) + "\n"
                if activity == .oracle, let i = fixtures.firstIndex(where: { $0.0.name == "two-alternating" }) {
                    let prepared = try await evaluator.prepared(i, embedding, activity)
                    let segments = evaluator.hypothesis(prepared, fixture: fixtures[i].0, configuration: configuration)
                    report += "Timeline, two-alternating:\n\n```\n" + Report.timeline(reference: fixtures[i].0.turns, hypothesis: segments) + "```\n\n"
                }
            }
        }
    }
    report += "## Separability (threshold-free)\n\nEqual error rate of a same/different-speaker decision over all pairs of single-speaker windows within each recording, oracle activity. Lower is better; 50 % is chance.\n\n| Fixture | " + evaluator.embeddings.map(\.name).joined(separator: " EER | ") + " EER |\n| --- |" + evaluator.embeddings.map { _ in " ---: |" }.joined() + "\n"
    var columns = [[Separability]]()
    for embedding in evaluator.embeddings { columns.append(try await evaluator.separability(embedding: embedding, indices: test)) }
    for row in columns[0].indices {
        report += "| \(columns[0][row].fixture) | " + columns.map { Report.pct($0[row].equalErrorRate) + " %" }.joined(separator: " | ") + " |\n"
    }
    try write(report, "evaluation.md")
    let encoder = JSONEncoder()
    encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
    try encoder.encode(all).write(to: resultsDirectory.appendingPathComponent("evaluation.json"))
}

func align(_ fixtures: [(RenderedFixture, [Float])]) async throws {
    let scripts = Dictionary(uniqueKeysWithValues: corpus().map { ($0.name, $0.turns) })
    var report = "# Transcript alignment\n\nRecognised words are traced to the script turn they came from by word-level edit-distance alignment, independent of timestamps. A *mixed final* is one finalised SpeechTranscriber result — one ScribeKit passage — containing aligned words from more than one speaker. Timing errors compare the recogniser's word ranges with where each turn's audio was placed (negative = early).\n\n"
    report += "| Fixture | Finals | Mixed finals | Words in mixed finals | Finals starting ≥0.3 s before their speech | Turn start error, median (max) | Turn end error, median (min) |\n| --- | ---: | ---: | ---: | ---: | ---: | ---: |\n"
    var finals = 0, mixed = 0, mixedWords = 0, words = 0, silence = 0
    var starts = [Double](), ends = [Double]()
    func median(_ v: [Double]) -> Double { v.isEmpty ? 0 : v.sorted()[v.count / 2] }
    for (fixture, _) in fixtures where fixture.split == "test" {
        let result = try await Alignment.finals(for: fixtureDirectory.appendingPathComponent("\(fixture.name).wav"))
        let row = Alignment.analyse(fixture: fixture, script: scripts[fixture.name]!, finals: result)
        report += "| \(row.fixture) | \(row.finals) | \(row.mixedFinals) | \(row.wordsInMixedFinals) of \(row.alignedWords) | \(row.finalsStartingInSilence) | "
        report += String(format: "%+.2f s (%+.2f) | %+.2f s (%+.2f) |\n", median(row.turnStartErrors), row.turnStartErrors.max() ?? 0, median(row.turnEndErrors), row.turnEndErrors.min() ?? 0)
        finals += row.finals; mixed += row.mixedFinals; mixedWords += row.wordsInMixedFinals; words += row.alignedWords; silence += row.finalsStartingInSilence
        starts += row.turnStartErrors; ends += row.turnEndErrors
    }
    report += "| **all** | \(finals) | \(mixed) | \(mixedWords) of \(words) | \(silence) | "
    report += String(format: "%+.2f s (%+.2f) | %+.2f s (%+.2f) |\n", median(starts), starts.max() ?? 0, median(ends), ends.min() ?? 0)
    try write(report, "alignment.md")
}

func bench(_ fixtures: [(RenderedFixture, [Float])]) async throws {
    let rows = try await Bench.run(directory: fixtureDirectory, fixtures: fixtures)
    let host = ProcessInfo.processInfo
    var report = "# Performance\n\nHost: \(host.activeProcessorCount) cores, macOS \(host.operatingSystemVersionString), \(String(format: "%.0f", Double(host.physicalMemory) / 1_073_741_824)) GB. Release build. 10 minutes of corpus audio.\n\n"
    report += "| Phase | Wall (s) | CPU (s) | Real-time factor (CPU s / audio s) | Peak footprint (MB) | Note |\n| --- | ---: | ---: | ---: | ---: | --- |\n"
    for r in rows {
        let rtf = r.phase.contains("10 min") ? String(format: "%.4f", r.cpuSeconds / 600) : "–"
        report += "| \(r.phase) | \(String(format: "%.3f", r.wallSeconds)) | \(String(format: "%.3f", r.cpuSeconds)) | \(rtf) | \(String(format: "%.1f", r.peakFootprintMB)) | \(r.note) |\n"
    }
    try write(report, "performance.md")
}

do {
    switch command {
    case "render": _ = try renderAll()
    case "evaluate": try await evaluate(renderAll())
    case "align": try await align(renderAll())
    case "bench": try await bench(renderAll())
    case "all":
        let fixtures = try renderAll()
        try await evaluate(fixtures)
        try await align(fixtures)
        try await bench(fixtures)
    default: throw LabError.usage("usage: diarization-lab <render|evaluate|align|bench|all>")
    }
} catch {
    FileHandle.standardError.write(Data("error: \(error)\n".utf8))
    exit(1)
}
