//
//  AudioFileWritingTests.swift
//  ScribeKitTests
//

import AVFAudio
import Foundation
import Testing
@testable import ScribeKit

/// The real `AVFAudio` writer, against a real temporary folder.
///
/// The doubles elsewhere prove the policy; these prove that the files it
/// produces are files: that a CAF and an M4A written buffer by buffer open
/// again afterwards, in the format ScribeKit said it would write, holding the
/// audio that was handed to them. Every sample here is a synthetic tone
/// generated by the test.
@Suite("Retained audio files")
struct AudioFileWritingTests {

    private let format = CapturedAudioFormat(
        sampleRate: 48_000,
        channelCount: 1,
        bitsPerChannel: 32,
        isFloat: true,
        isInterleaved: false
    )

    /// How many 20 ms buffers one second of capture delivers.
    private let buffersPerSecond = 50

    /// Frames in one delivered buffer, as ScreenCaptureKit sends them.
    private let framesPerBuffer = 960

    /// Runs work in a folder of its own, removed afterwards.
    ///
    /// - Parameter body: The work, given the folder.
    private func withFolder(_ body: (URL) throws -> Void) throws {
        let root = URL(filePath: NSTemporaryDirectory(), directoryHint: .isDirectory)
            .appending(path: "ScribeKitAudio-\(UUID().uuidString)", directoryHint: .isDirectory)
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: root) }
        try body(root)
    }

    /// The size of a file on disk, read afresh.
    ///
    /// `URL.resourceValues` caches, which would make a growing file look
    /// static; this asks the filesystem each time.
    ///
    /// - Parameter url: The file to measure.
    /// - Returns: Its size in bytes.
    private func size(of url: URL) throws -> Int {
        let attributes = try FileManager.default.attributesOfItem(atPath: url.path(percentEncoded: false))
        return try #require(attributes[.size] as? Int)
    }

    /// One buffer of a 440 Hz tone, continuing from a running phase.
    ///
    /// - Parameter phase: The oscillator's position, advanced in place.
    /// - Returns: A buffer of the shape capture delivers.
    private func tone(phase: inout Double) -> CapturedPCMBuffer {
        var samples = [Float](repeating: 0, count: framesPerBuffer)
        for index in 0..<framesPerBuffer {
            samples[index] = Float(sin(phase) * 0.4)
            phase += 2 * Double.pi * 440 / format.sampleRate
        }
        return CapturedPCMBuffer(
            format: format,
            frameCount: framesPerBuffer,
            presentationTime: nil,
            peakAmplitude: 0.4,
            samples: samples
        )
    }

    /// Writes a tone of a given length and closes the file.
    ///
    /// - Parameters:
    ///   - mode: What to keep.
    ///   - seconds: How much audio to write.
    ///   - directory: Where the session's artifacts go.
    /// - Returns: The file that was written.
    private func write(
        _ mode: AudioRetentionMode,
        seconds: Int,
        in directory: URL
    ) throws -> URL {
        let layout = SessionArtifactLayout(directory: directory)
        let url = try #require(layout.audioURL(for: mode))
        let writer = try AVAudioFileCreator().makeWriter(at: url, mode: mode, format: format)
        var phase = 0.0
        for _ in 0..<(seconds * buffersPerSecond) {
            try writer.write(tone(phase: &phase))
        }
        try writer.close()
        return url
    }

    @Test("Lossless audio is written to a CAF holding the captured format")
    func rawWritesLosslessCAF() throws {
        try withFolder { directory in
            let url = try write(.raw, seconds: 2, in: directory)

            let file = try AVAudioFile(forReading: url)
            #expect(url.lastPathComponent == "audio.caf")
            #expect(file.fileFormat.sampleRate == 48_000)
            #expect(file.fileFormat.channelCount == 1)
            #expect(file.fileFormat.commonFormat == .pcmFormatFloat32)
            #expect(file.length == 96_000)
        }
    }

    @Test("Compressed audio is written to a playable AAC file")
    func compressedWritesAAC() throws {
        try withFolder { directory in
            let url = try write(.compressed, seconds: 2, in: directory)

            let file = try AVAudioFile(forReading: url)
            let description = file.fileFormat.streamDescription.pointee
            #expect(url.lastPathComponent == "audio.m4a")
            #expect(description.mFormatID == kAudioFormatMPEG4AAC)
            #expect(file.fileFormat.sampleRate == 48_000)
            #expect(file.fileFormat.channelCount == 1)
            // AAC pads to a whole packet, so the length is the audio rounded up
            // rather than exactly the frames that went in.
            #expect(file.length >= 96_000)
            #expect(file.length < 96_000 + 2_048)
        }
    }

    @Test("Compressed audio is a fraction of the size of the same audio raw")
    func compressedIsSmallerThanRaw() throws {
        try withFolder { directory in
            // Both files live in one session directory only because this is a
            // test of their sizes; a real session keeps one or the other.
            let raw = try write(.raw, seconds: 4, in: directory)
            let compressed = try write(.compressed, seconds: 4, in: directory)

            #expect(try size(of: raw) > size(of: compressed) * 4)
        }
    }

    @Test("The file grows while the meeting runs rather than at the end")
    func fileGrowsIncrementally() throws {
        try withFolder { directory in
            let layout = SessionArtifactLayout(directory: directory)
            let url = try #require(layout.audioURL(for: .raw))
            let writer = try AVAudioFileCreator().makeWriter(at: url, mode: .raw, format: format)
            var phase = 0.0

            for _ in 0..<buffersPerSecond { try writer.write(tone(phase: &phase)) }
            let afterOneSecond = try size(of: url)
            for _ in 0..<(4 * buffersPerSecond) { try writer.write(tone(phase: &phase)) }
            let afterFive = try size(of: url)
            try writer.close()

            #expect(afterOneSecond > 0)
            #expect(afterFive > afterOneSecond)
        }
    }

    @Test("Audio in another format is refused rather than written")
    func mismatchedFormatIsRefused() throws {
        try withFolder { directory in
            let layout = SessionArtifactLayout(directory: directory)
            let url = try #require(layout.audioURL(for: .raw))
            let writer = try AVAudioFileCreator().makeWriter(at: url, mode: .raw, format: format)
            defer { try? writer.close() }

            let resampled = CapturedAudioFormat(
                sampleRate: 16_000,
                channelCount: 1,
                bitsPerChannel: 32,
                isFloat: true,
                isInterleaved: false
            )
            var thrown: AudioRetentionError?
            do {
                try writer.write(CapturedPCMBuffer(
                    format: resampled,
                    frameCount: 320,
                    presentationTime: nil,
                    peakAmplitude: 0.1,
                    samples: [Float](repeating: 0.1, count: 320)
                ))
            } catch {
                thrown = error as? AudioRetentionError
            }
            #expect(thrown?.reason == .unsupportedCapturedFormat)
        }
    }

    @Test("A file cannot be created in a folder that is not there")
    func creationFailsWithoutAFolder() throws {
        let missing = URL(filePath: NSTemporaryDirectory(), directoryHint: .isDirectory)
            .appending(path: "ScribeKitMissing-\(UUID().uuidString)", directoryHint: .isDirectory)
            .appending(path: "audio.caf", directoryHint: .notDirectory)

        var thrown: AudioRetentionError?
        do {
            _ = try AVAudioFileCreator().makeWriter(at: missing, mode: .raw, format: format)
        } catch {
            thrown = error as? AudioRetentionError
        }
        #expect(thrown?.reason == .cannotCreateAudioFile)
    }

    @Test("Keeping no audio is not a file that can be opened")
    func noneModeHasNoFile() throws {
        try withFolder { directory in
            let url = directory.appending(path: "audio.caf", directoryHint: .notDirectory)

            var thrown: AudioRetentionError?
            do {
                _ = try AVAudioFileCreator().makeWriter(at: url, mode: .none, format: format)
            } catch {
                thrown = error as? AudioRetentionError
            }
            #expect(thrown?.reason == .cannotCreateAudioFile)
            #expect(!FileManager.default.fileExists(atPath: url.path(percentEncoded: false)))
        }
    }

    @Test("A whole meeting's audio is written with one file and one encoder")
    func aLongRunIsWrittenIncrementally() throws {
        try withFolder { directory in
            // Sixty seconds of 20 ms buffers, written one at a time through the
            // recorder, with nothing between capture and the file.
            let creator = AVAudioFileCreator()
            let recorder = RetainedAudioRecorder(creator: creator)
            let layout = SessionArtifactLayout(directory: directory)
            let url = try #require(try recorder.startSession(mode: .compressed, layout: layout, format: format))
            var phase = 0.0
            for _ in 0..<(60 * buffersPerSecond) {
                recorder.consume(tone(phase: &phase))
            }
            try recorder.finishSession()

            let file = try AVAudioFile(forReading: url)
            #expect(recorder.retainedFrameCount == 60 * buffersPerSecond * framesPerBuffer)
            #expect(recorder.retainedDuration == 60)
            #expect(abs(Double(file.length) / file.fileFormat.sampleRate - 60) < 0.1)
        }
    }
}
